### ISSUE TITLE
Getting error when I reduce executor count.

### ISSUE THREAD

**Issue by MJFND** [awslabs/spark-sql-kinesis-connector#19]
I am using 4 executors with the following config:
```
        "cores"  = 3
        "memory" = "22g"
```
It works fine for 4 executors, but when I reduce the count to 3 it starts to throw the following:

```
 at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:332)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.$anonfun$run$1(StreamExecution.scala:211)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:211)
Caused by: org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase planning failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.
        at org.apache.spark.SparkException$.internalError(SparkException.scala:107)
        at org.apache.spark.sql.execution.QueryExecution$.toInternalError(QueryExecution.scala:536)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:548)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
```

Seems like a bug in the plugin.

**Comment by hwanghw** [comment]
can you upload the full stack trace?

**Comment by MJFND** [comment]
Will send, it seems like the issue is resolved by deleting the checkpoint
directory, I will keep posted if I see same behavior. Thanks
