### ISSUE TITLE
Unable to fetch committed metadata when I restart the job

### ISSUE THREAD

**Issue by satya-dd** [awslabs/spark-sql-kinesis-connector#26]
When I redeploy the spark streaming job, I notice this issue where the job fails to fetch committed metadata from Dynamodb. I set the startingposition to `TRIM_HORIZON`. The job is fine if I delete all the checkpoint entries in the dynamo table and restart it.

Any idea what might be causing this issue.

```
24/08/12 19:42:14 WARN ProcessingTimeExecutor: Current batch is falling behind. The trigger interval is 30000 milliseconds, but spent 176311 milliseconds
24/08/12 19:42:14 INFO KinesisV2MicrobatchStream: get latestOffset prevBatchId 2
24/08/12 19:42:14 INFO DynamodbMetadataCommitter: exists check from table stream_processor for batchId 2
24/08/12 19:42:14 INFO DynamodbMetadataCommitter: apply query limit 1.
24/08/12 19:42:14 INFO DynamodbMetadataCommitter: queryDataByBatchId- started from table stream_processor for batchId 2 with limit Some(1).
24/08/12 19:42:14 INFO DynamodbMetadataCommitter: queryDataByBatchId- lastEvaluatedKey was null - scan finished for batchId 2.
24/08/12 19:42:14 INFO DynamodbMetadataCommitter: queryDataByBatchId- Listed 0 item(s) from table stream_processor for batchId 2 with limit Some(1).
24/08/12 19:42:14 INFO package: reportTimeTaken queryDataByBatchId took 6 ms
24/08/12 19:42:14 INFO KinesisV2MicrobatchStream: getBatchShardsInfo for batchId 2 doesn't exists
24/08/12 19:42:14 ERROR MicroBatchExecution: Query [id = ....., runId = ......] terminated with error
java.lang.IllegalStateException: Unable to fetch committed metadata from previous batch id 2. Some data may have been missed
	at org.apache.spark.sql.connector.kinesis.KinesisV2MicrobatchStream.latestOffset(KinesisV2MicrobatchStream.scala:231)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$4(MicroBatchExecution.scala:491)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:427)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:425)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:67)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$constructNextBatch$2(MicroBatchExecution.scala:490)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
```

**Comment by hwanghw** [comment]
It shows batch 2 data is not in dynamodb.  When you use dynamodb to save kinesis connector's metadata,  Spark Structured Streaming's checkpoint data (committed, offset, etc.) is still in the checkpoint location specified by your job.  You need to ensure the checkpoint data and dynamodb metadata are consistent.

**Comment by satya-dd** [comment]
ah, that makes sense. thanks for the quick clarification.
